server:
  port: 8080
  context-path: /blog-mindmap/

spring:
  profiles:
    active: dev

  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

  main:
    banner-mode: "off"

  mvc:
    throw-exception-if-no-handler-found: true

#  resources:
#    add-mappings: false

mybatis:
  mapperLocations: classpath:/mapper/*.xml
  typeAliasesPackage: com.github.ld000.domain

logging:
  config: classpath:log4j2.xml
